---
image: nixos/nix:latest

default:
  cache:
    paths:
      - .nix
  before_script:
    - test -d .nix || cp -a /nix .nix
    - mount --bind .nix /nix
    - mkdir -p /etc/nix
    - echo 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
    - nix-env -iA nixpkgs.nixFlakes nixpkgs.git

build:
  stage: build
  script:
    - nix build
    - nix build '.#ocamlPackages_4_10.p2p'
    - nix build '.#ocamlPackages_4_11.p2p'
    #- nix build '.#ocamlPackages_4_12.p2p'
